name = "TuringOccupancy"
uuid = "2ea649bb-2049-48e0-99ad-c2a54fea0b5f"
authors = ["vlucet <valentin.lucet@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
